import type { PizzaConfig } from '../../pizza/domain/pizza'
import { normalizeNotes } from './order'
import type { OrderItemPayload } from './order'

interface DraftLineBase {
  /** Client-side identity of the line; generated by the caller to keep this module pure. */
  lineId: string
  name: string
  quantity: number
  /** Raw note text as typed; normalized when the payload is built. */
  notes: string
}

/** A line in the order being composed on the waiter screen. Deliberately price-less. */
export type DraftLine =
  | (DraftLineBase & { kind: 'product'; productId: string })
  | (DraftLineBase & { kind: 'pizza'; pizza: PizzaConfig })

export interface NewProductLine {
  lineId: string
  productId: string
  name: string
}

export interface NewPizzaLine {
  lineId: string
  pizza: PizzaConfig
  name: string
  notes: string
}

/**
 * Adds a product to the draft. It merges into an existing line of the same product
 * only when that line has no notes (the server merges the same way); otherwise it appends.
 */
export function addToDraft(draft: DraftLine[], product: NewProductLine): DraftLine[] {
  const existing = draft.find(
    (line) => line.kind === 'product' && line.productId === product.productId && line.notes.trim() === '',
  )
  if (existing) return incrementDraftLine(draft, existing.lineId)
  return [...draft, { ...product, kind: 'product', quantity: 1, notes: '' }]
}

/** Adds a pizza as its own line: pizza lines are never merged. */
export function addPizzaToDraft(draft: DraftLine[], pizza: NewPizzaLine): DraftLine[] {
  return [...draft, { ...pizza, kind: 'pizza', quantity: 1 }]
}

/** Increases the quantity of a draft line by one. */
export function incrementDraftLine(draft: DraftLine[], lineId: string): DraftLine[] {
  return draft.map((line) => (line.lineId === lineId ? { ...line, quantity: line.quantity + 1 } : line))
}

/** Decreases a draft line by one, removing it when the quantity would reach zero. */
export function decrementDraftLine(draft: DraftLine[], lineId: string): DraftLine[] {
  return draft
    .map((line) => (line.lineId === lineId ? { ...line, quantity: line.quantity - 1 } : line))
    .filter((line) => line.quantity > 0)
}

/** Removes a line from the draft entirely, regardless of quantity. */
export function removeDraftLine(draft: DraftLine[], lineId: string): DraftLine[] {
  return draft.filter((line) => line.lineId !== lineId)
}

/** Replaces the note of a draft line. */
export function setDraftLineNotes(draft: DraftLine[], lineId: string, notes: string): DraftLine[] {
  return draft.map((line) => (line.lineId === lineId ? { ...line, notes } : line))
}

/** Sum of quantities across all draft lines. */
export function draftItemCount(draft: DraftLine[]): number {
  return draft.reduce((total, line) => total + line.quantity, 0)
}

/** Maps the draft to the payload sent to the server (ids, configs, quantities and notes only). */
export function draftToPayload(draft: DraftLine[]): OrderItemPayload[] {
  return draft.map((line): OrderItemPayload => {
    const notes = normalizeNotes(line.notes)
    const withNotes = notes === null ? {} : { notes }
    if (line.kind === 'pizza') {
      return { type: 'pizza', pizza: line.pizza, quantity: line.quantity, ...withNotes }
    }
    return { type: 'product', productId: line.productId, quantity: line.quantity, ...withNotes }
  })
}
